title: >-
  This is the portfolio and blog of Dr. Majid Al Qassimi in the realm of
  Woodworking and Design.
purpose:
  - name: engagement
    url: null
    item: 3386c409-f77a-4ff1-b158-ceea707eae6d
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 0.6875
  brandColors:
    - '#FCFCFC'
    - '#000000'
    - '#484848'
    - '#BBBBBB'
    - '#808080'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Greater Than
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1272401
layout_spectrum: 0.609319
