name: Greater Than
favicon: null
layout_spectrum: 1
title: This is the portfolio and blog of Dr. Majid Al Qassimi in the realm of Woodworking and Design.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: 3386c409-f77a-4ff1-b158-ceea707eae6d
    url: null
